### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by markstos** [ianprime0509/jsonrecipe-schema#3]
Isn't this obsoleted the Recipe JSON-LD schema format used by Google, Wordpress and others?

https://schema.org/Recipe

https://developers.google.com/search/docs/advanced/structured-data/recipe

**Comment by ianprime0509** [comment]
Yes, I would argue it is obsolete. In fact, it was obsolete even at the time I created it (since the same standards existed at the time), but I wasn't aware of them until later.

I have a lot of old repositories for stuff that never really went anywhere, and this is one of them; I suppose I should archive it to prevent any confusion.
